# Generated by Django 5.0.6 on 2024-11-29 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='code',
        ),
    ]
