# Generated by Django 5.1.2 on 2024-12-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_color_code_alter_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
