# Generated by Django 5.1.2 on 2024-12-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
